<?php View::content(); ?>
<div class="row">
    <div class="col-md-4">&nbsp;</div>
    <div class="col-md-4"><h3>Editar Cuenta<h3></div>
    <div class="col-md-4">&nbsp;</div>  
    <div class="col-md-12">
        <table class="table table-striped">
            <tr>
             <th>Id</th>
             <th>Login</th>
             <th>Nombre</th>
             <th>Apellido</th>
             <th>Correo</th>
             <th>Fecha Nacimiento</th>
             <th>Fono</th>
            </tr>
            <?php foreach($page->items as $p): ?>
            <tr>
             <td><?php echo Html::link('usuarios/mod_usuario/'.$p->usro_id,$p->usro_id); ?></td>
             <td><?php echo $p->usro_login; ?></td>
             <td><?php echo $p->usro_nombre; ?></td>
             <td><?php echo $p->usro_apellido; ?></td>
             <td><?php echo $p->usro_correo; ?></td>
             <td><?php echo $p->usro_nac; ?></td>
             <td><?php echo $p->usro_fono; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>

            <?php View::partial('paginators/classic', false, array('page' => $page, 'show' => 5, 'url' => 'usuarios/lista_usuarios')); ?>
    </div>    
</div>
        <?php// echo Form::dbSelect('usuarios_id',$show = 'usro_login', $data = NULL, $blank = "Seleccione..", $attrs = "onchange='trae_cuenta(this.value);'"); ?>