<?php View::content(); ?>
<div class="row">
    <div class="col-md-4">&nbsp;</div>
    <div class="col-md-4"><h3>Listado de Usuarios<h3></div>
    <div class="col-md-4">&nbsp;</div>  
    <div class="col-md-12">&nbsp;</div>
    <div class="col-md-4">&nbsp;</div>
    <div class="col-md-4">
        <select class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <div class="col-md-4">&nbsp;</div>        
</div>