<?php View::content(); ?>
<div class="row">
    <div class="col-md-4">&nbsp;</div>
    <div class="col-md-4"><h3>Crear Cuenta<h3></div>
    <div class="col-md-4">&nbsp;</div>  
    <div class="col-md-12">&nbsp;</div>
    <?php echo Form::open("","POST","class= 'form-horizontal'"); ?>
        <div class="form-group">
            <?php echo Form::label("Login","usuarios_usro_login","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::text("usuarios.usro_login"," class='form-control' placeholder='Login'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Password","usuarios_usro_pass","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::pass("usuarios.usro_pass","class='form-control' placeholder='Password'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Nombre","usuarios_usro_nombre","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::text("usuarios.usro_nombre"," class='form-control' placeholder='Nombre'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Apellido","usuarios_usro_apellido","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::text("usuarios.usro_apellido"," class='form-control' placeholder='Apellido'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Email","usuarios_usro_apellido","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::email("usuarios.usro_correo","class='form-control' placeholder='Email'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Fecha Nacimiento","usuarios_usro_nac","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::date("usuarios.usro_nac"," class='form-control' placeholder='Fecha Nacimiento'"); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Tipo Usuario","usuarios_tpo_usro","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10 radio">
                <label>
                <?php echo Form::radio("usuarios.tpo_usro", '1', NULL, NULL);  ?>
                    Administrador&nbsp;&nbsp;&nbsp;
                </label>
                <label>
                <?php echo Form::radio("usuarios.tpo_usro", '2', NULL, NULL);  ?>
                Gestor&nbsp;&nbsp;&nbsp;
                </label>
                <label>
                <?php echo Form::radio("usuarios.tpo_usro", '3', NULL, NULL);  ?>
                Residente&nbsp;&nbsp;&nbsp;
                </label>
            </div>
        </div>
        <div class="form-group">
            <?php echo Form::label("Fono","usuarios_usro_fono","class='col-sm-2 control-label'"); ?>
            <div class="col-sm-10">
            <?php echo Form::text("usuarios.usro_fono"," class='form-control' placeholder='Fono'"); ?>
            </div>
        </div>        
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
            <?php echo Form::hidden('usuarios.usro_id') ?>
            <?php echo Form::submit("Guardar","class='btn btn-success'"); ?>
            </div>
        </div>
    <?php echo Form::close(); ?>
</div>