<div class="row">
    <?php echo Form::open("index","POST","class= 'form-horizontal'"); ?>
  <div class="form-group">
      <?php echo Form::label("Email","inputEmail3","class='col-sm-2 control-label'"); ?>
    <div class="col-sm-10">
      <?php echo Form::text("inputEmail3","type='email' class='form-control' id='inputEmail3' placeholder='Email'"); ?>
    </div>
  </div>
  <div class="form-group">
      <?php echo Form::label("Password","inputPassword3","class='col-sm-2 control-label'"); ?>
    <div class="col-sm-10">
      <?php echo Form::pass("inputPassword3","type='password' class='form-control' id='inputPassword3' placeholder='Password'"); ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <?php echo Form::submit("Sign in","class='btn btn-default'"); ?>
    </div>
  </div>
    <?php echo Form::close(); ?>
</div>



